/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Form_HasilAkhir extends javax.swing.JPanel {
    private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form Form_HasilAkhir
     */
    public Form_HasilAkhir() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_rank = new javax.swing.JTable();
        bt_update = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel1.setText("Rangking");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 51, -1, -1));

        tb_rank.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        tb_rank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_rank.setRowHeight(20);
        jScrollPane1.setViewportView(tb_rank);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 200, 874, -1));

        bt_update.setBackground(new java.awt.Color(255, 255, 255));
        bt_update.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        bt_update.setText("Update");
        bt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateActionPerformed(evt);
            }
        });
        add(bt_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    protected void datahasilAkhir(){
        Object[] Baris ={"Rangking","Nama","Hasil Akhir"};
        tabmode = new DefaultTableModel(null, Baris);
        tb_rank.setModel(tabmode);
        String sql = "SELECT * FROM tb_hasilakhir ORDER BY Hasil_Akhir DESC";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            int i = 1;
            while(hasil.next()){
                String a = Integer.toString(i);
                String b = hasil.getString("Nama");
                String c = hasil.getString("Hasil_Akhir");
                
                String[] data={a, b, c};
                tabmode.addRow(data);
                i++;
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void bt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateActionPerformed
        datahasilAkhir();
    }//GEN-LAST:event_bt_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_rank;
    // End of variables declaration//GEN-END:variables
}
