/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Form_User extends javax.swing.JPanel {
    private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form Form_User
     */
    public Form_User() {
        initComponents();
        dataadmintable();
        auto_code();
        b_Hapus.setVisible(false);
        b_Batal.setVisible(false);
    }
    protected void aktif(){
        t_Id.setEnabled(true);
        t_Nama.setEnabled(true);
        t_Username.setEnabled(true);
        t_Password.setEnabled(true);
        t_Nama.requestFocus();
    }
    protected void kosong(){
        auto_code();
        t_Nama.setText("");
        t_Username.setText("");
        t_Password.setText("");
        cb_Jabatan.setSelectedIndex(0);
    }
    
    protected void dataadmintable(){
        Object[] Baris ={"Id","Nama","Username","Password","Jabatan"};
        tabmode = new DefaultTableModel(null, Baris);
        tb_User.setModel(tabmode);
        String sql = "select * from tb_user";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
            String a = hasil.getString("id");
            String b = hasil.getString("nama");
            String c = hasil.getString("username");
            String d = hasil.getString("password");
            String e = hasil.getString("jabatan");
            
            String [] data = {a,b,c,d,e};
            tabmode.addRow(data);
            }
        }catch (Exception e){
        }
    }
    
    private void auto_code(){
    try{
        String sql = "select max(id) as id_adm from tb_user ";
        PreparedStatement stat = conn.prepareStatement(sql);
        ResultSet rs = stat.executeQuery(sql);
        while(rs.next()){
            Object [] obj = new Object[1];
            obj[0] = rs.getString("id_adm");
            if(obj[0] == null){
                obj[0] = "ADM000";
            }
            String str_kd = (String) obj[0];
            String kd = str_kd.substring(3,6);
            int int_code = Integer.parseInt(kd);
            int_code++;
            String a = String.format("%03d", int_code);
            String b = "ADM" + a;
            t_Id.setText(b);
            t_Id.setEditable(false);
            }
        }   catch (SQLException ex) {
          ex.printStackTrace();
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        b_Tambah = new javax.swing.JButton();
        b_Hapus = new javax.swing.JButton();
        b_Batal = new javax.swing.JButton();
        t_Id = new javax.swing.JTextField();
        t_Username = new javax.swing.JTextField();
        t_Nama = new javax.swing.JTextField();
        t_Password = new javax.swing.JTextField();
        cb_Jabatan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_User = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 83, 25));
        jLabel1.setText("Form User");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel2.setText("ID Petugas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 100, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel6.setText("Level");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, -1));

        b_Tambah.setBackground(new java.awt.Color(255, 255, 255));
        b_Tambah.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Tambah.setForeground(new java.awt.Color(0, 153, 51));
        b_Tambah.setText("Tambah");
        b_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_TambahActionPerformed(evt);
            }
        });
        jPanel1.add(b_Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 288, 110, 40));

        b_Hapus.setBackground(new java.awt.Color(255, 255, 255));
        b_Hapus.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Hapus.setForeground(new java.awt.Color(255, 0, 0));
        b_Hapus.setText("Hapus");
        b_Hapus.setPreferredSize(new java.awt.Dimension(91, 29));
        b_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_HapusActionPerformed(evt);
            }
        });
        jPanel1.add(b_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 288, 110, 40));

        b_Batal.setBackground(new java.awt.Color(255, 255, 255));
        b_Batal.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Batal.setText("Batal");
        b_Batal.setPreferredSize(new java.awt.Dimension(91, 29));
        b_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_BatalActionPerformed(evt);
            }
        });
        jPanel1.add(b_Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(954, 288, 100, 40));

        t_Id.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jPanel1.add(t_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 189, 234, 41));

        t_Username.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jPanel1.add(t_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 189, 234, 41));

        t_Nama.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jPanel1.add(t_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 288, 234, 41));

        t_Password.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jPanel1.add(t_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 288, 234, 41));

        cb_Jabatan.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        cb_Jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Kepala Sekolah" }));
        jPanel1.add(cb_Jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 190, 166, 39));

        tb_User.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        tb_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_User.setRowHeight(23);
        tb_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_User);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 361, 945, 414));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_TambahActionPerformed
      if (b_Tambah.getText().equals("Ubah")){
            try {
                String sql = "UPDATE tb_user SET nama=?, username=?, password=?, jabatan=? WHERE id=?";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, t_Nama.getText());
                stat.setString(2, t_Username.getText());
                stat.setString(3, t_Password.getText());
                stat.setString(4, cb_Jabatan.getSelectedItem().toString());
                stat.setString(5, t_Id.getText()); 

                int rowsUpdated = stat.executeUpdate();
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                    kosong();
                    t_Nama.requestFocus();
                    dataadmintable();
                    b_Tambah.setText("Tambah");
                    b_Hapus.setVisible(false);
                    b_Batal.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            }
        }else{
        String sql = "Insert into tb_user values (?,?,?,?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, t_Id.getText());
                stat.setString(2, t_Nama.getText());
                stat.setString(3, t_Username.getText());
                stat.setString(4, t_Password.getText());
                stat.setString(5, cb_Jabatan.getSelectedItem().toString());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Tambah");
                kosong();
                t_Nama.requestFocus();
                dataadmintable(); 
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Di Tambah");
            }
        }
    }//GEN-LAST:event_b_TambahActionPerformed

    private void tb_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_UserMouseClicked
        b_Tambah.setText("Ubah");
        b_Hapus.setVisible(true);
        b_Batal.setVisible(true);
        int bar = tb_User.getSelectedRow();
        String a =tabmode.getValueAt(bar, 0).toString();
        String b =tabmode.getValueAt(bar, 1).toString();
        String c =tabmode.getValueAt(bar, 2).toString();
        String d =tabmode.getValueAt(bar, 3).toString();
        String e =tabmode.getValueAt(bar, 4).toString();
        
        
        t_Id.setText(a);
        t_Nama.setText(b);
        t_Username.setText(c);
        t_Password.setText(d);
        cb_Jabatan.setSelectedItem(e);
    }//GEN-LAST:event_tb_UserMouseClicked

    private void b_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_HapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from tb_user where id ='"+t_Id.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                t_Nama.requestFocus();
                dataadmintable();
                b_Hapus.setVisible(false);
                b_Batal.setVisible(false);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" +e);
            }
        }
    }//GEN-LAST:event_b_HapusActionPerformed

    private void b_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_BatalActionPerformed
        kosong();
        b_Tambah.setText("Tambah");
        b_Hapus.setVisible(false);
        b_Batal.setVisible(false);
    }//GEN-LAST:event_b_BatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Batal;
    private javax.swing.JButton b_Hapus;
    private javax.swing.JButton b_Tambah;
    private javax.swing.JComboBox<String> cb_Jabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_Id;
    private javax.swing.JTextField t_Nama;
    private javax.swing.JTextField t_Password;
    private javax.swing.JTextField t_Username;
    private javax.swing.JTable tb_User;
    // End of variables declaration//GEN-END:variables
}
