package Form;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Year;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Form_Guru extends javax.swing.JPanel {
    private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form Form_Guru
     */
    public Form_Guru() {
        initComponents();
        datadaftartable();
        auto_code();
        b_Hapus.setVisible(false);
        b_Batal.setVisible(false);
    }
    protected void aktif(){
        t_IdGuru.setEnabled(true);
        t_Nama.setEnabled(true);
        t_Alamat.setEnabled(true);
        t_Nama.requestFocus();
    }
    
    protected void kosong(){
        auto_code();
        t_Nama.setText("");
        t_Alamat.setText("");
        rb_Jkl.setSelected(true);
        t_Tempat.setText("");
        t_Tanggal.setCalendar(null);
        t_Agama.setText("");
        t_Email.setText("");
    }
    
    protected void datadaftartable(){
        Object[] Baris ={"ID.Guru","Nama","Jenis Kelamin","Tmpt Lahir","Tgl Lahir","Agama","Email","Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        tb_DtGuru.setModel(tabmode);
        String sql = "select * from tb_guru";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
            String a = hasil.getString("id_guru");
            String b = hasil.getString("nama");
            String c = hasil.getString("jenis_kelamin");
            String d = hasil.getString("tempat");
            String e = "";
            java.sql.Date tanggalLahirSQL = hasil.getDate("tgl_lahir");
            if (tanggalLahirSQL != null) {
                Date tanggalLahirUtil = new Date(tanggalLahirSQL.getTime());
                SimpleDateFormat dateFormat = new SimpleDateFormat("MMM d,yyyy");
                e = dateFormat.format(tanggalLahirUtil);
            }
            String f = hasil.getString("agama");
            String g = hasil.getString("email");
            String h = hasil.getString("alamat");
            
            String [] data = {a,b,c,d,e,f,g,h};
            tabmode.addRow(data);
            }
        }catch (Exception e){
        }
    }
    
    private void auto_code() {
    try {
        String sql = "SELECT MAX(id_guru) AS no FROM tb_guru";
        PreparedStatement stat = conn.prepareStatement(sql);
        ResultSet rs = stat.executeQuery();

        int currentYear = Year.now().getValue(); // Inisialisasi currentYear di luar loop while
        int int_code = 0;

        while (rs.next()) {
            String str_kd = rs.getString("no");
            if (str_kd == null) {
                int_code = 0;
            } else {
                String kd = str_kd.substring(7); // Mengambil 3 karakter terakhir setelah tahun
                int_code = Integer.parseInt(kd);
            }
        }

        int_code = int_code + 1;
        String a = String.format("%03d", int_code);
        String b = "IDG" + currentYear + "" + a;
        t_IdGuru.setText(b);
        t_IdGuru.setEditable(false);
        } 
        catch (SQLException ex) {
        ex.printStackTrace();
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJK = new javax.swing.ButtonGroup();
        main_Panel = new javax.swing.JPanel();
        pn_dataGuru = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b_Batal = new javax.swing.JButton();
        b_Tambah = new javax.swing.JButton();
        b_Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_DtGuru = new javax.swing.JTable();
        t_caridaftar = new javax.swing.JTextField();
        b_cari = new javax.swing.JButton();
        pn_TambahDtguru = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        b_Batal1 = new javax.swing.JButton();
        b_Tambah1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t_IdGuru = new javax.swing.JTextField();
        t_Nama = new javax.swing.JTextField();
        t_Email = new javax.swing.JTextField();
        t_Tempat = new javax.swing.JTextField();
        t_Agama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_Alamat = new javax.swing.JTextArea();
        rb_Jkl = new javax.swing.JRadioButton();
        rb_Jkp = new javax.swing.JRadioButton();
        t_Tanggal = new com.toedter.calendar.JDateChooser();

        main_Panel.setLayout(new java.awt.CardLayout());

        pn_dataGuru.setBackground(new java.awt.Color(255, 255, 255));
        pn_dataGuru.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 83, 25));
        jLabel1.setText("Data Guru");
        pn_dataGuru.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        b_Batal.setBackground(new java.awt.Color(255, 255, 255));
        b_Batal.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Batal.setText("Batal");
        b_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_BatalActionPerformed(evt);
            }
        });
        pn_dataGuru.add(b_Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 110, 40));

        b_Tambah.setBackground(new java.awt.Color(255, 255, 255));
        b_Tambah.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Tambah.setForeground(new java.awt.Color(0, 153, 51));
        b_Tambah.setText("Tambah");
        b_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_TambahActionPerformed(evt);
            }
        });
        pn_dataGuru.add(b_Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, 40));

        b_Hapus.setBackground(new java.awt.Color(255, 255, 255));
        b_Hapus.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Hapus.setForeground(new java.awt.Color(255, 0, 0));
        b_Hapus.setText("Hapus");
        b_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_HapusActionPerformed(evt);
            }
        });
        pn_dataGuru.add(b_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, 40));

        tb_DtGuru.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        tb_DtGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_DtGuru.setRowHeight(25);
        tb_DtGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_DtGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_DtGuru);

        pn_dataGuru.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 1400, 500));

        t_caridaftar.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        t_caridaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_caridaftarActionPerformed(evt);
            }
        });
        pn_dataGuru.add(t_caridaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 180, 200, 40));

        b_cari.setBackground(new java.awt.Color(255, 255, 255));
        b_cari.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_cari.setText("Cari");
        b_cari.setPreferredSize(new java.awt.Dimension(77, 31));
        b_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cariActionPerformed(evt);
            }
        });
        pn_dataGuru.add(b_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 180, 110, 40));

        main_Panel.add(pn_dataGuru, "card2");

        pn_TambahDtguru.setBackground(new java.awt.Color(255, 255, 255));
        pn_TambahDtguru.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 83, 25));
        jLabel2.setText("Tambah Data Guru");
        pn_TambahDtguru.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        b_Batal1.setBackground(new java.awt.Color(255, 255, 255));
        b_Batal1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Batal1.setForeground(new java.awt.Color(255, 0, 51));
        b_Batal1.setText("Batal");
        b_Batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_Batal1ActionPerformed(evt);
            }
        });
        pn_TambahDtguru.add(b_Batal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, 40));

        b_Tambah1.setBackground(new java.awt.Color(255, 255, 255));
        b_Tambah1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Tambah1.setForeground(new java.awt.Color(0, 153, 51));
        b_Tambah1.setText("Simpan");
        b_Tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_Tambah1ActionPerformed(evt);
            }
        });
        pn_TambahDtguru.add(b_Tambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel3.setText("ID Guru");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel4.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel6.setText("Tempat");

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel7.setText("Tanggal Lahir");

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel8.setText("Agama");

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel10.setText("Alamat");

        t_IdGuru.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        t_Nama.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        t_Email.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        t_Tempat.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        t_Agama.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        t_Alamat.setColumns(20);
        t_Alamat.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        t_Alamat.setRows(5);
        jScrollPane2.setViewportView(t_Alamat);

        rb_Jkl.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupJK.add(rb_Jkl);
        rb_Jkl.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        rb_Jkl.setText("Laki-Laki");

        rb_Jkp.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupJK.add(rb_Jkp);
        rb_Jkp.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        rb_Jkp.setText("Perempuan");

        t_Tanggal.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(210, 210, 210))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(t_Nama)
                                    .addGap(80, 80, 80)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_IdGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(80, 80, 80)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_Tempat, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(t_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_Agama, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_Jkl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_Jkp)))
                        .addGap(50, 50, 50)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_IdGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_Tempat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(44, 44, 44))
                        .addComponent(t_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(t_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rb_Jkl)
                                    .addComponent(rb_Jkp)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(t_Agama, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pn_TambahDtguru.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1030, 510));

        main_Panel.add(pn_TambahDtguru, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1477, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_BatalActionPerformed
        b_Tambah.setText("Tambah");
        b_Hapus.setVisible(false);
        b_Batal.setVisible(false);
    }//GEN-LAST:event_b_BatalActionPerformed

    private void b_Batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_Batal1ActionPerformed
        main_Panel.removeAll();
        main_Panel.add(pn_dataGuru);
        main_Panel.repaint();
        main_Panel.revalidate();
        b_Tambah.setText("Tambah");
        b_Hapus.setVisible(false);
        b_Batal.setVisible(false);
    }//GEN-LAST:event_b_Batal1ActionPerformed

    private void b_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_TambahActionPerformed
        main_Panel.removeAll();
        main_Panel.repaint();
        main_Panel.revalidate();
    if (b_Tambah.getText().equals("Ubah")){
        main_Panel.add(pn_TambahDtguru);
        main_Panel.repaint();
        main_Panel.revalidate();
        b_Tambah1.setText("Edit");
    }else if (b_Tambah.getText().equals("Tambah")){
        main_Panel.add(pn_TambahDtguru);
        main_Panel.repaint();
        main_Panel.revalidate();
        b_Tambah1.setText("Simpan");
        kosong();
        t_Nama.requestFocus();
        }
    }//GEN-LAST:event_b_TambahActionPerformed

    private void tb_DtGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_DtGuruMouseClicked
        b_Tambah.setText("Ubah");
        b_Batal.setVisible(true);
        b_Hapus.setVisible(true);
        int bar = tb_DtGuru.getSelectedRow();
        String a =tabmode.getValueAt(bar, 0).toString();
        String b =tabmode.getValueAt(bar, 1).toString();
        String c =tabmode.getValueAt(bar, 2).toString();
        String d =tabmode.getValueAt(bar, 3).toString();
        String e =tabmode.getValueAt(bar, 4).toString();
        String f =tabmode.getValueAt(bar, 5).toString();
        String g =tabmode.getValueAt(bar, 6).toString();
        String h =tabmode.getValueAt(bar, 7).toString();
        
        
        t_IdGuru.setText(a);
        t_Nama.setText(b);

        if(c.equals("Laki-Laki")) {rb_Jkl.setSelected(true); rb_Jkp.setSelected(false);}
        else{rb_Jkl.setSelected(false); rb_Jkp.setSelected(true);}

        t_Tempat.setText(d);
        try {
        SimpleDateFormat dateFormat = new SimpleDateFormat("MMM d,yyyy");
        Date tanggal = dateFormat.parse(e);
        t_Tanggal.setDate(tanggal);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        t_Agama.setText(f);
        t_Email.setText(g);
        t_Alamat.setText(h);
    }//GEN-LAST:event_tb_DtGuruMouseClicked

    private void b_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_HapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from tb_guru where id_guru ='"+t_IdGuru.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                t_Nama.requestFocus();
                datadaftartable();
                b_Tambah.setText("Tambah");
                b_Hapus.setVisible(false);
                b_Batal.setVisible(false);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" +e);
            }
        }
    }//GEN-LAST:event_b_HapusActionPerformed

    private void b_Tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_Tambah1ActionPerformed
        if (b_Tambah1.getText().equals("Edit")){
             try {
                String sql = "UPDATE tb_guru SET nama=?, jenis_kelamin=?, tempat=?, tgl_lahir=?, agama=?, email=?, alamat=? WHERE id_guru=?";
                PreparedStatement stat = conn.prepareStatement(sql);

                stat.setString(1, t_Nama.getText());

                String jkel = "";
                if (rb_Jkl.isSelected()) {
                    jkel = "Laki-Laki";
                } else {
                    jkel = "Perempuan";
                }
                stat.setString(2, jkel);

                stat.setString(3, t_Tempat.getText());

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String tanggal = sdf.format(t_Tanggal.getDate());
                stat.setString(4, tanggal);

                stat.setString(5, t_Agama.getText());
                stat.setString(6, t_Email.getText());
                stat.setString(7, t_Alamat.getText());
                stat.setString(8, t_IdGuru.getText());
                
                b_Tambah.setText("Tambah");
                b_Hapus.setVisible(false);
                b_Batal.setVisible(false);
                int rowsUpdated = stat.executeUpdate();
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                    main_Panel.removeAll();
                    main_Panel.repaint();
                    main_Panel.revalidate();
                    main_Panel.add(pn_dataGuru);
                    main_Panel.repaint();
                    main_Panel.revalidate();
                    kosong();
                    t_Nama.requestFocus();
                    datadaftartable();
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah: " + e.getMessage());
            }
        }else{
        String sql = "Insert into tb_guru (id_guru,nama,jenis_kelamin,tempat,tgl_lahir,agama,email,alamat) values (?,?,?,?,?,?,?,?)";
        try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, t_IdGuru.getText());
                stat.setString(2, t_Nama.getText());

                String jkel = "";
                if (rb_Jkl.isSelected()) {
                    jkel = "Laki-Laki";
                } else {
                    jkel = "Perempuan";
                }
                stat.setString(3, jkel);

                stat.setString(4, t_Tempat.getText());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String tanggal = sdf.format(t_Tanggal.getDate());
                stat.setString(5, tanggal);
                stat.setString(6, t_Agama.getText());
                stat.setString(7, t_Email.getText());
                stat.setString(8, t_Alamat.getText());

                int rowsAffected = stat.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                    main_Panel.removeAll();
                    main_Panel.repaint();
                    main_Panel.revalidate();
                    main_Panel.add(pn_dataGuru);
                    main_Panel.repaint();
                    main_Panel.revalidate();
                    datadaftartable();
                    kosong();
                    b_Tambah.setText("Tambah");
                    b_Hapus.setVisible(false);
                    b_Batal.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_b_Tambah1ActionPerformed

    private void t_caridaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_caridaftarActionPerformed
        String searchTerm = t_caridaftar.getText().trim(); // Kata kunci pencarian (dengan spasi dihilangkan)
    
        String sql = "SELECT * FROM tb_guru";
    
        if (!searchTerm.isEmpty()) {
        sql += " WHERE id_guru LIKE ? OR nama LIKE ?";
        }
    
        try {
        PreparedStatement stat = conn.prepareStatement(sql);
        
        if (!searchTerm.isEmpty()) {
            stat.setString(1, "%" + searchTerm + "%");
            stat.setString(2, "%" + searchTerm + "%");
        }
        
        ResultSet hasil = stat.executeQuery();
        
        DefaultTableModel newModel = new DefaultTableModel();
        newModel.setColumnIdentifiers(new Object[] {"ID.Guru","Nama","Jenis Kelamin","Tmpt Lahir","Tgl Lahir","Agama","Email","Alamat"});
        
        while (hasil.next()){
            String a = hasil.getString("id_guru");
            String b = hasil.getString("nama");
            String c = hasil.getString("jenis_kelamin");
            String d = hasil.getString("tempat");
            String e = "";
            java.sql.Date tanggalLahirSQL = hasil.getDate("tgl_lahir");
            if (tanggalLahirSQL != null) {
                Date tanggalLahirUtil = new Date(tanggalLahirSQL.getTime());
                SimpleDateFormat dateFormat = new SimpleDateFormat("MMM d,yyyy");
                e = dateFormat.format(tanggalLahirUtil);
            }
            String f = hasil.getString("agama");
            String g = hasil.getString("email");
            String h = hasil.getString("alamat");
            
            String [] data = {a,b,c,d,e,f,g,h};
            newModel.addRow(data);
        }
        
        tb_DtGuru.setModel(newModel); // Mengganti model tabel dengan model yang baru
        
        stat.close();
        }catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_t_caridaftarActionPerformed

    private void b_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cariActionPerformed
        String searchTerm = t_caridaftar.getText().trim(); // Kata kunci pencarian (dengan spasi dihilangkan)
    
        String sql = "SELECT * FROM tb_guru";
    
        if (!searchTerm.isEmpty()) {
        sql += " WHERE id_guru LIKE ? OR nama LIKE ?";
        }
    
        try {
        PreparedStatement stat = conn.prepareStatement(sql);
        
        if (!searchTerm.isEmpty()) {
            stat.setString(1, "%" + searchTerm + "%");
            stat.setString(2, "%" + searchTerm + "%");
        }
        
        ResultSet hasil = stat.executeQuery();
        
        DefaultTableModel newModel = new DefaultTableModel();
        newModel.setColumnIdentifiers(new Object[] {"ID.Guru","Nama","Jenis Kelamin","Tmpt Lahir","Tgl Lahir","Agama","Email","Alamat"});
        
        while (hasil.next()){
            String a = hasil.getString("id_guru");
            String b = hasil.getString("nama");
            String c = hasil.getString("jenis_kelamin");
            String d = hasil.getString("tempat");
            String e = "";
            java.sql.Date tanggalLahirSQL = hasil.getDate("tgl_lahir");
            if (tanggalLahirSQL != null) {
                Date tanggalLahirUtil = new Date(tanggalLahirSQL.getTime());
                SimpleDateFormat dateFormat = new SimpleDateFormat("MMM d,yyyy");
                e = dateFormat.format(tanggalLahirUtil);
            }
            String f = hasil.getString("agama");
            String g = hasil.getString("email");
            String h = hasil.getString("alamat");
            
            String [] data = {a,b,c,d,e,f,g,h};
            newModel.addRow(data);
        }
        
        tb_DtGuru.setModel(newModel); // Mengganti model tabel dengan model yang baru
        
        stat.close();
        }catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_b_cariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Batal;
    private javax.swing.JButton b_Batal1;
    private javax.swing.JButton b_Hapus;
    private javax.swing.JButton b_Tambah;
    private javax.swing.JButton b_Tambah1;
    private javax.swing.JButton b_cari;
    private javax.swing.ButtonGroup buttonGroupJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel main_Panel;
    private javax.swing.JPanel pn_TambahDtguru;
    private javax.swing.JPanel pn_dataGuru;
    private javax.swing.JRadioButton rb_Jkl;
    private javax.swing.JRadioButton rb_Jkp;
    private javax.swing.JTextField t_Agama;
    private javax.swing.JTextArea t_Alamat;
    private javax.swing.JTextField t_Email;
    private javax.swing.JTextField t_IdGuru;
    private javax.swing.JTextField t_Nama;
    private com.toedter.calendar.JDateChooser t_Tanggal;
    private javax.swing.JTextField t_Tempat;
    private javax.swing.JTextField t_caridaftar;
    private javax.swing.JTable tb_DtGuru;
    // End of variables declaration//GEN-END:variables
}
