/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Form_Rangking extends javax.swing.JPanel {
    Connection conn = new Koneksi().connect();
    
    /**
     * Creates new form Form_Rangking
     */
    public Form_Rangking() {
        initComponents();
        combo();
        combo1();
        combo2();
        combo3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_hasilPasuji = new javax.swing.JTextField();
        t_KpKriteria = new javax.swing.JTextField();
        t_PrKriteria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_PdKriteria = new javax.swing.JTextField();
        t_hasilPaiman = new javax.swing.JTextField();
        t_hasilPaseto = new javax.swing.JTextField();
        b_Hitung = new javax.swing.JButton();
        t_hasilPaijo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        b_LoadKriteria = new javax.swing.JButton();
        t_SoKriteria = new javax.swing.JTextField();
        t_paijo1 = new javax.swing.JTextField();
        t_paiman1 = new javax.swing.JTextField();
        t_paseto1 = new javax.swing.JTextField();
        t_pasuji1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        b_loadAlternatif = new javax.swing.JButton();
        t_paijo2 = new javax.swing.JTextField();
        t_paiman2 = new javax.swing.JTextField();
        t_paseto2 = new javax.swing.JTextField();
        t_pasuji2 = new javax.swing.JTextField();
        t_paseto3 = new javax.swing.JTextField();
        t_paijo3 = new javax.swing.JTextField();
        t_paiman3 = new javax.swing.JTextField();
        t_pasuji3 = new javax.swing.JTextField();
        t_paiman4 = new javax.swing.JTextField();
        t_paseto4 = new javax.swing.JTextField();
        t_pasuji4 = new javax.swing.JTextField();
        t_paijo4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cb_alt1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cb_alt2 = new javax.swing.JComboBox<>();
        cb_alt3 = new javax.swing.JComboBox<>();
        cb_alt4 = new javax.swing.JComboBox<>();
        b_Simpan1 = new javax.swing.JButton();
        b_Simpan2 = new javax.swing.JButton();
        b_Simpan3 = new javax.swing.JButton();
        b_Simpan4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel1.setText("Sosial");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel3.setText("Pasuji");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel4.setText("Kepribadian");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel5.setText("Profesional");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        t_hasilPasuji.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_hasilPasuji, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 710, 160, 40));

        t_KpKriteria.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        t_KpKriteria.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        add(t_KpKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 160, 40));

        t_PrKriteria.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        t_PrKriteria.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        add(t_PrKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 160, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 0, 24)); // NOI18N
        jLabel6.setText("Alternatif");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, -1, -1));

        t_PdKriteria.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        t_PdKriteria.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        add(t_PdKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 160, 40));

        t_hasilPaiman.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_hasilPaiman, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 160, 40));

        t_hasilPaseto.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_hasilPaseto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 160, 40));

        b_Hitung.setForeground(new java.awt.Color(0, 153, 51));
        b_Hitung.setText("Hitung");
        b_Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_HitungActionPerformed(evt);
            }
        });
        add(b_Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 760, 100, 35));

        t_hasilPaijo.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_hasilPaijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 160, 40));

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 51));
        jLabel13.setText("Hasil Akhir");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel14.setText("Pedagogik");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        jLabel15.setText("Profesional");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel16.setText("Paijo");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel17.setText("Paiman");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel18.setText("Paseto");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        b_LoadKriteria.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_LoadKriteria.setText("Load");
        b_LoadKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_LoadKriteriaActionPerformed(evt);
            }
        });
        add(b_LoadKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 90, 40));

        t_SoKriteria.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        t_SoKriteria.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        add(t_SoKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 160, 40));

        t_paijo1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paijo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 100, 35));

        t_paiman1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paiman1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 100, 35));

        t_paseto1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paseto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 100, 35));

        t_pasuji1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_pasuji1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 100, 35));

        jLabel19.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        jLabel19.setText("Pedagogik");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

        jLabel31.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        jLabel31.setText("Sosial");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 160, -1, -1));

        jLabel34.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        jLabel34.setText("Kepribadian");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, -1, -1));

        b_loadAlternatif.setText("Load");
        b_loadAlternatif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loadAlternatifActionPerformed(evt);
            }
        });
        add(b_loadAlternatif, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 100, 35));

        t_paijo2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paijo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 100, 35));

        t_paiman2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paiman2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 100, 35));

        t_paseto2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paseto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 100, 35));

        t_pasuji2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_pasuji2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 100, 35));

        t_paseto3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paseto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 300, 100, 35));

        t_paijo3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paijo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 100, 35));

        t_paiman3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paiman3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 250, 100, 35));

        t_pasuji3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_pasuji3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 100, 35));

        t_paiman4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paiman4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 250, 100, 35));

        t_paseto4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paseto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 300, 100, 35));

        t_pasuji4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_pasuji4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 350, 100, 35));

        t_paijo4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_paijo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 100, 35));

        jLabel20.setFont(new java.awt.Font("Lucida Fax", 0, 24)); // NOI18N
        jLabel20.setText("Kriteria");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        cb_alt1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(cb_alt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 120, -1));

        jLabel21.setFont(new java.awt.Font("Lucida Fax", 0, 24)); // NOI18N
        jLabel21.setText("Hasil Akhir");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        cb_alt2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(cb_alt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, 120, -1));

        cb_alt3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(cb_alt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 120, -1));

        cb_alt4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(cb_alt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 720, 120, -1));

        b_Simpan1.setForeground(new java.awt.Color(0, 153, 51));
        b_Simpan1.setText("Simpan");
        b_Simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_Simpan1ActionPerformed(evt);
            }
        });
        add(b_Simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 100, 35));

        b_Simpan2.setForeground(new java.awt.Color(0, 153, 51));
        b_Simpan2.setText("Simpan");
        b_Simpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_Simpan2ActionPerformed(evt);
            }
        });
        add(b_Simpan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, 100, 35));

        b_Simpan3.setForeground(new java.awt.Color(0, 153, 51));
        b_Simpan3.setText("Simpan");
        b_Simpan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_Simpan3ActionPerformed(evt);
            }
        });
        add(b_Simpan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, 100, 35));

        b_Simpan4.setForeground(new java.awt.Color(0, 153, 51));
        b_Simpan4.setText("Simpan");
        b_Simpan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_Simpan4ActionPerformed(evt);
            }
        });
        add(b_Simpan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, 100, 35));
    }// </editor-fold>//GEN-END:initComponents
       
    private void nilaiPaijo(){
        String sql = "SELECT Paijo FROM tb_penilaianalternatif";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hsl = stat.executeQuery(sql);
            int count = 1;    while (hsl.next() && count <= 4) {
              String nilai = hsl.getString("Paijo");
                switch (count) {
                case 1:
                    t_paijo1.setText(nilai);
                    break;
                case 2:
                    t_paijo2.setText(nilai);
                    break;
                case 3:
                    t_paijo3.setText(nilai);
                    break;
                case 4:
                    t_paijo4.setText(nilai);
                    break;
                default:
                    break;
        }
        count++;
        }
        }catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }             
    } 
    
    private void nilaiPaiman(){
        String sql = "SELECT Paiman FROM tb_penilaianalternatif";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hsl = stat.executeQuery(sql);
            int count = 1;    while (hsl.next() && count <= 4) {
              String nilai = hsl.getString("Paiman");
                switch (count) {
                case 1:
                    t_paiman1.setText(nilai);
                    break;
                case 2:
                    t_paiman2.setText(nilai);
                    break;
                case 3:
                    t_paiman3.setText(nilai);
                    break;
                case 4:
                    t_paiman4.setText(nilai);
                    break;
                default:
                    break;
        }
        count++;
        }
        }catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }             
    }
    
    private void nilaiPaseto(){
        String sql = "SELECT Paseto FROM tb_penilaianalternatif";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hsl = stat.executeQuery(sql);
            int count = 1;    while (hsl.next() && count <= 4) {
              String nilai = hsl.getString("Paseto");
                switch (count) {
                case 1:
                    t_paseto1.setText(nilai);
                    break;
                case 2:
                    t_paseto2.setText(nilai);
                    break;
                case 3:
                    t_paseto3.setText(nilai);
                    break;
                case 4:
                    t_paseto4.setText(nilai);
                    break;
                default:
                    break;
        }
        count++;
        }
        }catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }             
    }
    
    private void nilaiPasuji(){
        String sql = "SELECT Pasuji FROM tb_penilaianalternatif";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hsl = stat.executeQuery(sql);
            int count = 1;    while (hsl.next() && count <= 4) {
              String nilai = hsl.getString("Pasuji");
                switch (count) {
                case 1:
                    t_pasuji1.setText(nilai);
                    break;
                case 2:
                    t_pasuji2.setText(nilai);
                    break;
                case 3:
                    t_pasuji3.setText(nilai);
                    break;
                case 4:
                    t_pasuji4.setText(nilai);
                    break;
                default:
                    break;
        }
        count++;
        }
        }catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }             
    }
  
    private void hitung(){
        //Alternatif
        float paijo1 = Float.parseFloat(t_paijo1.getText());
        float paijo2 = Float.parseFloat(t_paijo2.getText());
        float paijo3 = Float.parseFloat(t_paijo3.getText());
        float paijo4 = Float.parseFloat(t_paijo4.getText());
        
        float paiman1 = Float.parseFloat(t_paiman1.getText());
        float paiman2 = Float.parseFloat(t_paiman2.getText());
        float paiman3 = Float.parseFloat(t_paiman3.getText());
        float paiman4 = Float.parseFloat(t_paiman4.getText());
        
        float paseto1 = Float.parseFloat(t_paseto1.getText());
        float paseto2 = Float.parseFloat(t_paseto2.getText());
        float paseto3 = Float.parseFloat(t_paseto3.getText());
        float paseto4 = Float.parseFloat(t_paseto4.getText());
        
        float pasuji1 = Float.parseFloat(t_pasuji1.getText());
        float pasuji2 = Float.parseFloat(t_pasuji2.getText());
        float pasuji3 = Float.parseFloat(t_pasuji3.getText());
        float pasuji4 = Float.parseFloat(t_pasuji4.getText());
        
        //KriteriaA
        float pedagogik = Float.parseFloat(t_PdKriteria.getText());
        float kepribadian = Float.parseFloat(t_KpKriteria.getText());
        float profesional = Float.parseFloat(t_PrKriteria.getText());
        float sosial = Float.parseFloat(t_SoKriteria.getText());
        
        float hitungPaijo = (pedagogik*paijo1) + (kepribadian*paijo2) + (profesional*paijo3) + (sosial*paijo4);
            String total = String.format("%.3f", hitungPaijo);
            t_hasilPaijo.setText(total);
            
        float hitungPaiman = (pedagogik*paiman1) + (kepribadian*paiman2) + (profesional*paiman3) + (sosial*paiman4);
            String total1 = String.format("%.3f", hitungPaiman);
            t_hasilPaiman.setText(total1);
            
        float hitungPaseto = (pedagogik*paseto1) + (kepribadian*paseto2) + (profesional*paseto3) + (sosial*paseto4);
            String total2 = String.format("%.3f", hitungPaseto);
            t_hasilPaseto.setText(total2); 
        
        float hitungPasuji = (pedagogik*pasuji1) + (kepribadian*pasuji2) + (profesional*pasuji3) + (sosial*pasuji4);
            String total3 = String.format("%.3f", hitungPasuji);
            t_hasilPasuji.setText(total3);
    }
    
    private void combo(){
        String sql = "SELECT DISTINCT nama FROM tb_guru ORDER BY nama asc;";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String b = hasil.getString("nama");
                cb_alt1.addItem(b);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void combo1(){
        String sql = "SELECT DISTINCT nama FROM tb_guru ORDER BY nama asc;";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String b = hasil.getString("nama");
                cb_alt2.addItem(b);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void combo2(){
        String sql = "SELECT DISTINCT nama FROM tb_guru ORDER BY nama asc;";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String b = hasil.getString("nama");
                cb_alt3.addItem(b);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void combo3(){
        String sql = "SELECT DISTINCT nama FROM tb_guru ORDER BY nama asc;";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String b = hasil.getString("nama");
                cb_alt4.addItem(b);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void b_loadAlternatifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loadAlternatifActionPerformed
        nilaiPaijo();
        nilaiPaiman();
        nilaiPaseto();
        nilaiPasuji();
    }//GEN-LAST:event_b_loadAlternatifActionPerformed

    private void b_HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_HitungActionPerformed
        hitung();
    }//GEN-LAST:event_b_HitungActionPerformed

    private void b_LoadKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_LoadKriteriaActionPerformed
        String sql = "Select * From tb_penilaiankriteria";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hsl = stat.executeQuery(sql);
            while(hsl.next()){
                String k1 = hsl.getString("Pedagogik");
                t_PdKriteria.setText(k1);
                String k2 = hsl.getString("Kepribadian");
                t_KpKriteria.setText(k2);
                String k3 = hsl.getString("Profesional");
                t_PrKriteria.setText(k3);
                String k4 = hsl.getString("Sosial");
                t_SoKriteria.setText(k4);

                t_PdKriteria.setEnabled(false);
                t_KpKriteria.setEnabled(false);
                t_PrKriteria.setEnabled(false);
                t_SoKriteria.setEnabled(false);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_b_LoadKriteriaActionPerformed

    private void b_Simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_Simpan1ActionPerformed
        String sql = "Insert into tb_hasilakhir values (?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, cb_alt1.getSelectedItem().toString());
                stat.setString(2, t_hasilPaijo.getText());
                
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Tambah");
                
                cb_alt1.requestFocus(); 
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Di Tambah");
            }
    }//GEN-LAST:event_b_Simpan1ActionPerformed

    private void b_Simpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_Simpan2ActionPerformed
        String sql = "Insert into tb_hasilakhir values (?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, cb_alt2.getSelectedItem().toString());
                stat.setString(2, t_hasilPaiman.getText());
                
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Tambah");
                
                cb_alt2.requestFocus(); 
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Di Tambah");
            }
    }//GEN-LAST:event_b_Simpan2ActionPerformed

    private void b_Simpan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_Simpan3ActionPerformed
        String sql = "Insert into tb_hasilakhir values (?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, cb_alt3.getSelectedItem().toString());
                stat.setString(2, t_hasilPaseto.getText());
                
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Tambah");
                
                cb_alt3.requestFocus(); 
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Di Tambah");
            }
    }//GEN-LAST:event_b_Simpan3ActionPerformed

    private void b_Simpan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_Simpan4ActionPerformed
        String sql = "Insert into tb_hasilakhir values (?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, cb_alt4.getSelectedItem().toString());
                stat.setString(2, t_hasilPasuji.getText());
                
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Tambah");
                
                cb_alt4.requestFocus(); 
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Di Tambah");
            }
    }//GEN-LAST:event_b_Simpan4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Hitung;
    private javax.swing.JButton b_LoadKriteria;
    private javax.swing.JButton b_Simpan1;
    private javax.swing.JButton b_Simpan2;
    private javax.swing.JButton b_Simpan3;
    private javax.swing.JButton b_Simpan4;
    private javax.swing.JButton b_loadAlternatif;
    private javax.swing.JComboBox<String> cb_alt1;
    private javax.swing.JComboBox<String> cb_alt2;
    private javax.swing.JComboBox<String> cb_alt3;
    private javax.swing.JComboBox<String> cb_alt4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField t_KpKriteria;
    private javax.swing.JTextField t_PdKriteria;
    private javax.swing.JTextField t_PrKriteria;
    private javax.swing.JTextField t_SoKriteria;
    private javax.swing.JTextField t_hasilPaijo;
    private javax.swing.JTextField t_hasilPaiman;
    private javax.swing.JTextField t_hasilPaseto;
    private javax.swing.JTextField t_hasilPasuji;
    private javax.swing.JTextField t_paijo1;
    private javax.swing.JTextField t_paijo2;
    private javax.swing.JTextField t_paijo3;
    private javax.swing.JTextField t_paijo4;
    private javax.swing.JTextField t_paiman1;
    private javax.swing.JTextField t_paiman2;
    private javax.swing.JTextField t_paiman3;
    private javax.swing.JTextField t_paiman4;
    private javax.swing.JTextField t_paseto1;
    private javax.swing.JTextField t_paseto2;
    private javax.swing.JTextField t_paseto3;
    private javax.swing.JTextField t_paseto4;
    private javax.swing.JTextField t_pasuji1;
    private javax.swing.JTextField t_pasuji2;
    private javax.swing.JTextField t_pasuji3;
    private javax.swing.JTextField t_pasuji4;
    // End of variables declaration//GEN-END:variables
}
