/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;
import Koneksi.Koneksi;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Form_penilaianKriteria extends javax.swing.JPanel {
    Connection conn = new Koneksi().connect();
    private float hasil_jum2 = 0;
    private float hasil_jum3 = 0;
    private float hasil_jum4 = 0;
    private float hasil_jum5 = 0;
    private float hasil_jum6 = 0;
    private float hasil_jum7 = 0;
    private float hasil_jum8 = 0;
    private float hasil_jum9 = 0;
    private float hasil_jum10 = 0;
    private float hasil_jum11 = 0;
    private float hasil_jum12 = 0;
    private float hasil_jum13 = 0;
    private float hasil_jum14 = 0;
    private float hasil_jum15 = 0;
    private float hasil_jum16 = 0;
    private float hasil_jum17 = 0;
    private float hasil_jum18 = 0;
    private float hasil_jum19 = 0;
    private float hasil_jum20 = 0;
    private float hasil_jum21 = 0;
    private float hasil_jum22 = 0;
    private float hasil_jum23 = 0;
    /**
     * Creates new form Form_penilaianKriteria
     */
    public Form_penilaianKriteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t_Sos4 = new javax.swing.JTextField();
        t_Sos1 = new javax.swing.JTextField();
        t_Sos2 = new javax.swing.JTextField();
        t_Sos3 = new javax.swing.JTextField();
        t_Pd1 = new javax.swing.JTextField();
        t_Kp1 = new javax.swing.JTextField();
        t_Pr1 = new javax.swing.JTextField();
        t_Pd2 = new javax.swing.JTextField();
        t_Kp2 = new javax.swing.JTextField();
        t_Pr2 = new javax.swing.JTextField();
        t_Pd3 = new javax.swing.JTextField();
        t_Kp3 = new javax.swing.JTextField();
        t_Pr3 = new javax.swing.JTextField();
        t_Sosial1 = new javax.swing.JTextField();
        t_Kp4 = new javax.swing.JTextField();
        t_Pr4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        t_Pd4 = new javax.swing.JTextField();
        t_Pdg1 = new javax.swing.JTextField();
        t_Kpb1 = new javax.swing.JTextField();
        t_Pro1 = new javax.swing.JTextField();
        t_Sosial2 = new javax.swing.JTextField();
        t_Pro2 = new javax.swing.JTextField();
        t_Kpb2 = new javax.swing.JTextField();
        t_Pdg2 = new javax.swing.JTextField();
        t_Pdg3 = new javax.swing.JTextField();
        t_Kpb3 = new javax.swing.JTextField();
        t_Pro3 = new javax.swing.JTextField();
        t_Sosial3 = new javax.swing.JTextField();
        t_Pdg4 = new javax.swing.JTextField();
        t_Kpb4 = new javax.swing.JTextField();
        t_Pro4 = new javax.swing.JTextField();
        t_Sosial4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        t_Jumlah1 = new javax.swing.JTextField();
        t_Jumlah2 = new javax.swing.JTextField();
        t_Jumlah3 = new javax.swing.JTextField();
        SoBobot = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        t_Jum1 = new javax.swing.JTextField();
        t_Jum2 = new javax.swing.JTextField();
        t_Jum3 = new javax.swing.JTextField();
        t_Jum4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        t_Jumlah4 = new javax.swing.JTextField();
        PdBobot = new javax.swing.JTextField();
        KpBobot = new javax.swing.JTextField();
        PrBobot = new javax.swing.JTextField();
        CR = new javax.swing.JTextField();
        Kp_Persen = new javax.swing.JTextField();
        Pr_Persen = new javax.swing.JTextField();
        So_Persen = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Pd_Persen = new javax.swing.JTextField();
        Lamb_max = new javax.swing.JTextField();
        C_Indeks = new javax.swing.JTextField();
        C_Rasio = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        EG1 = new javax.swing.JTextField();
        EG2 = new javax.swing.JTextField();
        EG3 = new javax.swing.JTextField();
        EG4 = new javax.swing.JTextField();
        b_Simpan = new javax.swing.JButton();
        b_Hitung = new javax.swing.JButton();
        b_Reset = new javax.swing.JButton();
        t_kodePerhitungan = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 83, 25));
        jLabel1.setText("Penilaian Kriteria");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel2.setText("Matriks Perbandingan Berpasangan");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("CR < 0.1");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 710, 140, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel4.setText("Matriks Nilai Kriteria");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel5.setText("Pedagogik");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 110, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel6.setText("Kepribadian");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel7.setText("Profesional");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 110, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel8.setText("Pedagogik");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel9.setText("Kepribadian");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel10.setText("Profesional");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 110, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("Jumlah");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 110, -1));

        t_Sos4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Sos4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Sos4.setText("1");
        add(t_Sos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 110, 40));

        t_Sos1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Sos1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Sos1.setPreferredSize(new java.awt.Dimension(6, 28));
        add(t_Sos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 110, 40));

        t_Sos2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Sos2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Sos2.setPreferredSize(new java.awt.Dimension(6, 28));
        add(t_Sos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 110, 40));

        t_Sos3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Sos3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Sos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 110, 40));

        t_Pd1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Pd1.setText("1");
        t_Pd1.setPreferredSize(new java.awt.Dimension(6, 28));
        add(t_Pd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 110, 40));

        t_Kp1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Kp1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Kp1.setPreferredSize(new java.awt.Dimension(6, 28));
        add(t_Kp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, 40));

        t_Pr1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pr1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Pr1.setPreferredSize(new java.awt.Dimension(6, 28));
        add(t_Pr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 110, 40));

        t_Pd2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pd2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Pd2.setPreferredSize(new java.awt.Dimension(6, 28));
        t_Pd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Pd2ActionPerformed(evt);
            }
        });
        add(t_Pd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 110, 40));

        t_Kp2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Kp2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Kp2.setText("1");
        t_Kp2.setPreferredSize(new java.awt.Dimension(6, 28));
        add(t_Kp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 110, 40));

        t_Pr2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pr2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Pr2.setPreferredSize(new java.awt.Dimension(6, 28));
        add(t_Pr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 110, 40));

        t_Pd3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pd3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Pd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Pd3ActionPerformed(evt);
            }
        });
        add(t_Pd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 110, 40));

        t_Kp3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Kp3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Kp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Kp3ActionPerformed(evt);
            }
        });
        add(t_Kp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 110, 40));

        t_Pr3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pr3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Pr3.setText("1");
        add(t_Pr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 110, 40));

        t_Sosial1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Sosial1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Sosial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, 110, 40));

        t_Kp4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Kp4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Kp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Kp4ActionPerformed(evt);
            }
        });
        add(t_Kp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 110, 40));

        t_Pr4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pr4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Pr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Pr4ActionPerformed(evt);
            }
        });
        add(t_Pr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 110, 40));

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel12.setText("Kode Perhitungan");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel13.setText("Pedagogik");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 110, -1));

        jLabel14.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel14.setText("Kepribadian");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel15.setText("Profesional");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 110, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel16.setText("Sosial");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 70, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel17.setText("Pedagogik");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 110, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel18.setText("Kepribadian");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel19.setText("Profesional");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 110, -1));

        jLabel20.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 51));
        jLabel20.setText("Jumlah");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 140, 70, -1));

        t_Pd4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pd4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Pd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_Pd4ActionPerformed(evt);
            }
        });
        add(t_Pd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 110, 40));

        t_Pdg1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pdg1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Pdg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 110, 40));

        t_Kpb1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Kpb1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Kpb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 110, 40));

        t_Pro1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pro1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Pro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 110, 40));

        t_Sosial2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Sosial2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Sosial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 410, 110, 40));

        t_Pro2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pro2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Pro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 340, 110, 40));

        t_Kpb2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Kpb2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Kpb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 110, 40));

        t_Pdg2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pdg2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Pdg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, 110, 40));

        t_Pdg3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pdg3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Pdg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, 110, 40));

        t_Kpb3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Kpb3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Kpb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, 110, 40));

        t_Pro3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pro3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Pro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, 110, 40));

        t_Sosial3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Sosial3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Sosial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 410, 110, 40));

        t_Pdg4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pdg4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Pdg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 200, 110, 40));

        t_Kpb4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Kpb4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Kpb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 270, 110, 40));

        t_Pro4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Pro4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Pro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 340, 110, 40));

        t_Sosial4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Sosial4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Sosial4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 410, 110, 40));

        jLabel21.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel21.setText("Sosial");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 140, 60, -1));

        t_Jumlah1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Jumlah1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Jumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 200, 110, 40));

        t_Jumlah2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Jumlah2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Jumlah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 270, 110, 40));

        t_Jumlah3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Jumlah3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Jumlah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 340, 110, 40));

        SoBobot.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        SoBobot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(SoBobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 700, 110, 40));

        jLabel22.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel22.setText("Sosial");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 110, -1));

        t_Jum1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Jum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Jum1.setPreferredSize(new java.awt.Dimension(6, 28));
        add(t_Jum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 110, 40));

        t_Jum2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Jum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_Jum2.setPreferredSize(new java.awt.Dimension(6, 28));
        add(t_Jum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 110, 40));

        t_Jum3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Jum3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Jum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 110, 40));

        t_Jum4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Jum4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Jum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 110, 40));

        jLabel23.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel23.setText("Sosial");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 70, -1));

        jLabel24.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel24.setText("Hasil Perhitungan");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 480, 170, -1));

        jLabel25.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel25.setText("Pedagogik");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 100, -1));

        jLabel26.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel26.setText("Kepribadian");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, 110, -1));

        jLabel27.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel27.setText("Profesional");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, 110, -1));

        jLabel28.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel28.setText("Sosial");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 710, 110, -1));

        jLabel29.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel29.setText("Bobot");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 520, 80, -1));

        t_Jumlah4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        t_Jumlah4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(t_Jumlah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 410, 110, 40));

        PdBobot.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        PdBobot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(PdBobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 110, 40));

        KpBobot.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        KpBobot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(KpBobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 600, 110, 40));

        PrBobot.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        PrBobot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(PrBobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 650, 110, 40));

        CR.setFont(new java.awt.Font("Lucida Fax", 0, 16)); // NOI18N
        CR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(CR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 700, 180, 40));

        Kp_Persen.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        Kp_Persen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Kp_Persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 110, 40));

        Pr_Persen.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        Pr_Persen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Pr_Persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 650, 110, 40));

        So_Persen.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        So_Persen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(So_Persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 700, 110, 40));

        jLabel30.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel30.setText("Nilai Bobot");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 110, -1));

        jLabel31.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel31.setText("Persentase");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 520, 100, -1));

        jLabel32.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel32.setText("Lambda Max");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 120, -1));

        jLabel33.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel33.setText("Consistency Indeks (CI)");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 590, 220, -1));

        jLabel34.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel34.setText("Consistency Rasio (CR)");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 650, 220, -1));

        Pd_Persen.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        Pd_Persen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Pd_Persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 550, 110, 40));

        Lamb_max.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        Lamb_max.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Lamb_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 520, 110, 40));

        C_Indeks.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        C_Indeks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(C_Indeks, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 580, 110, 40));

        C_Rasio.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        C_Rasio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(C_Rasio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 640, 110, 40));

        jLabel35.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel35.setText("Eigen Vector");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 140, 120, -1));

        EG1.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        EG1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(EG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 200, 110, 40));

        EG2.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        EG2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(EG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 270, 110, 40));

        EG3.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        EG3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(EG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 340, 110, 40));

        EG4.setFont(new java.awt.Font("Lucida Fax", 0, 20)); // NOI18N
        EG4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(EG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 410, 110, 40));

        b_Simpan.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Simpan.setForeground(new java.awt.Color(0, 153, 51));
        b_Simpan.setText("Simpan");
        b_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_SimpanActionPerformed(evt);
            }
        });
        add(b_Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 110, 40));

        b_Hitung.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Hitung.setText("Hitung");
        b_Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_HitungActionPerformed(evt);
            }
        });
        add(b_Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 110, 40));

        b_Reset.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        b_Reset.setForeground(new java.awt.Color(255, 0, 0));
        b_Reset.setText("Reset");
        b_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ResetActionPerformed(evt);
            }
        });
        add(b_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 630, 110, 40));

        t_kodePerhitungan.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        add(t_kodePerhitungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void calculateSum(){
        float A = Float.parseFloat(t_Pd1.getText());
        float jum = A + hasil_jum2 + hasil_jum3 + hasil_jum4;
        String jumlah = String.format("%.3f", jum);
        t_Jum1.setText(jumlah);
    }
    private void calculateSum1(){
        float E = Float.parseFloat(t_Pd2.getText());
        float F = Float.parseFloat(t_Kp2.getText());
        float jum = E + F + hasil_jum5 + hasil_jum6;
        String jumlah = String.format("%.3f", jum);
        t_Jum2.setText(jumlah);
    }
    private void calculateSum2(){
        float I = Float.parseFloat(t_Pd3.getText());
        float J = Float.parseFloat(t_Kp3.getText());
        float K = Float.parseFloat(t_Pr3.getText());
        float jum = I + J + K + hasil_jum7;
        String jumlah = String.format("%.3f", jum);
        t_Jum3.setText(jumlah);
    }
    
    private void calculateSum3(){
        float M = Float.parseFloat(t_Pd4.getText());
        float N = Float.parseFloat(t_Kp4.getText());
        float O = Float.parseFloat(t_Pr4.getText());
        float P = Float.parseFloat(t_Sos4.getText());
        float jum = M + N + O + P;
        String jumlah = String.format("%.3f", jum);
        t_Jum4.setText(jumlah);
    }
    
    private void hitungbaris(){
        float A,AA,Jumlah1;
        Jumlah1 = Float.parseFloat(t_Jum1.getText());
        A = Float.parseFloat(t_Pd1.getText());
        AA = A / Jumlah1;
        hasil_jum8 = AA;
        String PD = String.format("%.3f", AA);
        t_Pdg1.setText(PD);
        
        float B,BB;
        B = Float.parseFloat(t_Kp1.getText());
        BB = B / Jumlah1;
        hasil_jum9= BB;
        String KP = String.format("%.3f", BB);
        t_Kpb1.setText(KP);
        
        float C,CC;
        C = Float.parseFloat(t_Pr1.getText());
        CC = C / Jumlah1;
        hasil_jum10 = CC;
        String PR = String.format("%.3f", CC);
        t_Pro1.setText(PR);
        
        float D,DD;
        D = Float.parseFloat(t_Sos1.getText());
        DD = D / Jumlah1;
        hasil_jum11 = DD;
        String SO = String.format("%.3f", DD);
        t_Sosial1.setText(SO);
    }
    private void hitungbaris1(){
        float E,EE,Jumlah2;
        Jumlah2 = Float.parseFloat(t_Jum2.getText());
        E = Float.parseFloat(t_Pd2.getText());
        EE = E / Jumlah2;
        hasil_jum12 = EE;
        String PD1 = String.format("%.3f", EE);
        t_Pdg2.setText(PD1);
        
        float F,FF;
        F = Float.parseFloat(t_Kp2.getText());
        FF = F / Jumlah2;
        hasil_jum13= FF;
        String KP1 = String.format("%.3f", FF);
        t_Kpb2.setText(KP1);
        
        float G,GG;
        G = Float.parseFloat(t_Pr2.getText());
        GG = G / Jumlah2;
        hasil_jum14 = GG;
        String PR1 = String.format("%.3f", GG);
        t_Pro2.setText(PR1);
        
        float H,HH;
        H = Float.parseFloat(t_Sos2.getText());
        HH = H / Jumlah2;
        hasil_jum15 = HH;
        String SS1 = String.format("%.3f", HH);
        t_Sosial2.setText(SS1);
    }
    private void hitungbaris2(){
        float I,II,Jumlah3;
        Jumlah3 = Float.parseFloat(t_Jum3.getText());
        I = Float.parseFloat(t_Pd3.getText());
        II = I / Jumlah3;
        hasil_jum16 = II;
        String PD2 = String.format("%.3f", II);
        t_Pdg3.setText(PD2);
        
        float J,JJ;
        J = Float.parseFloat(t_Kp3.getText());
        JJ = J / Jumlah3;
        hasil_jum17= JJ;
        String KP2 = String.format("%.3f", JJ);
        t_Kpb3.setText(KP2);
        
        float K,KK;
        K = Float.parseFloat(t_Pr3.getText());
        KK = K / Jumlah3;
        hasil_jum18 = KK;
        String PR2 = String.format("%.3f", KK);
        t_Pro3.setText(PR2);
        
        float L,LL;
        L = Float.parseFloat(t_Sos3.getText());
        LL = L / Jumlah3;
        hasil_jum19 = LL;
        String SS2 = String.format("%.3f", LL);
        t_Sosial3.setText(SS2);
    }
    private void hitungbaris3(){
        float M,MM,Jumlah4;
        Jumlah4 = Float.parseFloat(t_Jum4.getText());
        M = Float.parseFloat(t_Pd4.getText());
        MM = M / Jumlah4;
        hasil_jum20 = MM;
        String PD3 = String.format("%.3f", MM);
        t_Pdg4.setText(PD3);
        
        float N,NN;
        N = Float.parseFloat(t_Kp4.getText());
        NN = N / Jumlah4;
        hasil_jum21= NN;
        String KP3 = String.format("%.3f", NN);
        t_Kpb4.setText(KP3);
        
        float O,OO;
        O = Float.parseFloat(t_Pr4.getText());
        OO = O / Jumlah4;
        hasil_jum22 = OO;
        String PR3 = String.format("%.3f", OO);
        t_Pro4.setText(PR3);
        
        float P,PP;
        P = Float.parseFloat(t_Sos4.getText());
        PP = P / Jumlah4;
        hasil_jum23 = PP;
        String SS3 = String.format("%.3f", PP);
        t_Sosial4.setText(SS3);
    }
    private void jumlahbaris(){
        float Hasil1 = hasil_jum8 + hasil_jum12 + hasil_jum16 + hasil_jum20;
            String jumlah = String.format("%.3f", Hasil1);
            t_Jumlah1.setText(jumlah);
    }
    private void jumlahbaris1(){
        float Hasil2 = hasil_jum9 + hasil_jum13 + hasil_jum17 + hasil_jum21;
            String jumlah = String.format("%.3f", Hasil2);
            t_Jumlah2.setText(jumlah);
    }
    private void jumlahbaris2(){
        float Hasil3 = hasil_jum10 + hasil_jum14 + hasil_jum18 + hasil_jum22;
            String jumlah = String.format("%.3f", Hasil3);
            t_Jumlah3.setText(jumlah);
    }
    private void jumlahbaris3(){
        float Hasil4 = hasil_jum11 + hasil_jum15 + hasil_jum19 + hasil_jum23;
            String jumlah = String.format("%.3f", Hasil4);
            t_Jumlah4.setText(jumlah);
    }
    
    
    private void t_Pd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Pd2ActionPerformed
        float A, B, E;
        A = Float.parseFloat(t_Pd1.getText());
        E = Float.parseFloat(t_Pd2.getText());
        B = A / E;
        hasil_jum2 = B;
        String B1 = String.format("%.3f", B);
        t_Kp1.setText(B1);
    }//GEN-LAST:event_t_Pd2ActionPerformed

    private void t_Pd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Pd3ActionPerformed
        float A, I, C;
        A = Float.parseFloat(t_Pd1.getText());
        I = Float.parseFloat(t_Pd3.getText());
        C = A / I;
        hasil_jum3 = C;
        String B2 = String.format("%.3f", C);
        t_Pr1.setText(B2);
    }//GEN-LAST:event_t_Pd3ActionPerformed

    private void t_Pd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Pd4ActionPerformed
        float A, M, D;
        A = Float.parseFloat(t_Pd1.getText());
        M = Float.parseFloat(t_Pd4.getText());
        D = A / M;
        hasil_jum4 = D;
        String B3 = String.format("%.3f", D);
        t_Sos1.setText(B3);
        calculateSum();
    }//GEN-LAST:event_t_Pd4ActionPerformed

    private void t_Kp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Kp3ActionPerformed
        float F, J, G;
        F = Float.parseFloat(t_Kp2.getText());
        J = Float.parseFloat(t_Kp3.getText());
        G = F / J;
        hasil_jum5 = G;
        String B4 = String.format("%.3f", G);
        t_Pr2.setText(B4);
    }//GEN-LAST:event_t_Kp3ActionPerformed

    private void t_Kp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Kp4ActionPerformed
        float F, N, H;
        F = Float.parseFloat(t_Kp2.getText());
        N = Float.parseFloat(t_Kp4.getText());
        H = F / N;
        hasil_jum6 = H;
        String B5 = String.format("%.3f", H);
        t_Sos2.setText(B5);
        calculateSum1();
    }//GEN-LAST:event_t_Kp4ActionPerformed

    private void t_Pr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_Pr4ActionPerformed
        float K, O, L;
        K = Float.parseFloat(t_Pr4.getText());
        O = Float.parseFloat(t_Pr3.getText());
        L = O / K;
        hasil_jum7 = L;
        String B6 = String.format("%.3f", L);
        t_Sos3.setText(B6);
        calculateSum2();
        calculateSum3();
        hitungbaris();
        hitungbaris1();
        hitungbaris2();
        hitungbaris3();
        jumlahbaris();
        jumlahbaris1();
        jumlahbaris2();
        jumlahbaris3();
    }//GEN-LAST:event_t_Pr4ActionPerformed

    private void b_HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_HitungActionPerformed
        //Menghitung Nilai Bobot    
        float hslbagi1,hslbagi2,hslbagi3,hslbagi4,jumlah4,jumlah5,jumlah6,jumlah7;
        
        jumlah4 = Float.parseFloat(t_Jumlah1.getText());
        hslbagi1 = jumlah4 / 4;
        String hsbg1 = String.format("%.3f", hslbagi1);
        PdBobot.setText(hsbg1);
        
        jumlah5 = Float.parseFloat(t_Jumlah2.getText());
        hslbagi2 = jumlah5 / 4;
        String hsbg2 = String.format("%.3f", hslbagi2);
        KpBobot.setText(hsbg2);
        
        jumlah6 = Float.parseFloat(t_Jumlah3.getText());
        hslbagi3 = jumlah6 / 4;
        String hsbg3 = String.format("%.3f", hslbagi3);
        PrBobot.setText(hsbg3);
        
        jumlah7 = Float.parseFloat(t_Jumlah4.getText());
        hslbagi4 = jumlah7 / 4;
        String hsbg4 = String.format("%.3f", hslbagi4);
        SoBobot.setText(hsbg4);
        
        //Menghitung Persentase    
        float P1 = Float.parseFloat(PdBobot.getText());
        float persen1 = P1 * 100;
        Pd_Persen.setText(String.format("%.1f", persen1) + "%");
        
        float P2 = Float.parseFloat(KpBobot.getText());
        float persen2 = P2 * 100;
        Kp_Persen.setText(String.format("%.1f", persen2) + "%");
        
        float P3 = Float.parseFloat(PrBobot.getText());
        float persen3 = P3 * 100;
        Pr_Persen.setText(String.format("%.1f", persen3) + "%");
        
        float P4 = Float.parseFloat(SoBobot.getText());
        float persen4 = P4 * 100;
        So_Persen.setText(String.format("%.1f", persen4) + "%");
        
        //Menghitung Eigen Vektor    
        float jumpb1,jumpb2,jumpb3,jumpb4,nb1,nb2,nb3,nb4,eg1,eg2,eg3,eg4;
        
        jumpb1 = Float.parseFloat(t_Jum1.getText());
        nb1 = Float.parseFloat(PdBobot.getText());
        eg1 = jumpb1 * nb1;
        String nilaieg1 = String.format("%.3f", eg1);
        EG1.setText(nilaieg1);
        
        jumpb2 = Float.parseFloat(t_Jum2.getText());
        nb2 = Float.parseFloat(KpBobot.getText());
        eg2 = jumpb2 * nb2;
        String nilaieg2 = String.format("%.3f", eg2);
        EG2.setText(nilaieg2);
        
        jumpb3 = Float.parseFloat(t_Jum3.getText());
        nb3 = Float.parseFloat(PrBobot.getText());
        eg3 = jumpb3 * nb3;
        String nilaieg3 = String.format("%.3f", eg3);
        EG3.setText(nilaieg3);
        
        jumpb4 = Float.parseFloat(t_Jum4.getText());
        nb4 = Float.parseFloat(SoBobot.getText());
        eg4 = jumpb4 * nb4;
        String nilaieg4 = String.format("%.3f", eg4);
        EG4.setText(nilaieg4);
        
        //Hasil Perhitungan Akhir
        //Mencari nilai Maks
        float tev1 = Float.parseFloat(EG1.getText());
        float tev2 = Float.parseFloat(EG2.getText());
        float tev3 = Float.parseFloat(EG3.getText());
        float tev4 = Float.parseFloat(EG4.getText());
        float hasilmaks = tev1 + tev2 + tev3 + tev4;
        String maks = String.format("%.3f", hasilmaks);
        Lamb_max.setText(maks);
        
        //Mencari nilai CI
        float maks1 = Float.parseFloat(Lamb_max.getText());
        float hasilmaks1 = (maks1 - 4) / 3.0f;
        String maks2 = String.format("%.3f", hasilmaks1);
        C_Indeks.setText(maks2);
        
        //Mencari nilai CR
        float ci = Float.parseFloat(C_Indeks.getText());
        float hitungcr = ci / 0.9f;
        String cr1 = String.format("%.3f", hitungcr);
        C_Rasio.setText(cr1);
        
        //Kesimpulan konsisten atau tidak konsisten
        float verif = Float.parseFloat(C_Rasio.getText());
        
        if (verif < 0.1) {
            CR.setText("Konsisten");
        } else {
            CR.setText("Tidak Konsisten");
        } 
    }//GEN-LAST:event_b_HitungActionPerformed

    private void b_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SimpanActionPerformed
        String sql = "Insert into tb_penilaiankriteria values (?,?,?,?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, t_kodePerhitungan.getText());
                stat.setString(2, PdBobot.getText());
                stat.setString(3, KpBobot.getText());
                stat.setString(4, PrBobot.getText());
                stat.setString(5, SoBobot.getText());
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Tambah");
                
                t_kodePerhitungan.requestFocus(); 
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Di Tambah");
            }
    }//GEN-LAST:event_b_SimpanActionPerformed

    private void b_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ResetActionPerformed
        t_Pd2.setText(null);
        t_Pd3.setText(null);
        t_Pd4.setText(null);
        t_Kp1.setText(null);
        t_Kp3.setText(null);
        t_Kp4.setText(null);
        t_Pr1.setText(null);
        t_Pr2.setText(null);
        t_Pr4.setText(null);
        t_Sos1.setText(null);
        t_Sos2.setText(null);
        t_Sos3.setText(null);
        t_Jum1.setText(null);
        t_Jum2.setText(null);
        t_Jum3.setText(null);
        t_Jum4.setText(null);
        t_Pdg1.setText(null);
        t_Pdg2.setText(null);
        t_Pdg3.setText(null);
        t_Pdg4.setText(null);
        t_Kpb1.setText(null);
        t_Kpb2.setText(null);
        t_Kpb3.setText(null);
        t_Kpb4.setText(null);
        t_Pro1.setText(null);
        t_Pro2.setText(null);
        t_Pro3.setText(null);
        t_Pro4.setText(null);
        t_Sosial1.setText(null);
        t_Sosial2.setText(null);
        t_Sosial3.setText(null);
        t_Sosial4.setText(null);
        t_Jumlah1.setText(null);
        t_Jumlah2.setText(null);
        t_Jumlah3.setText(null);
        t_Jumlah4.setText(null);
        EG1.setText(null);
        EG2.setText(null);
        EG3.setText(null);
        EG4.setText(null);
        PdBobot.setText(null);
        KpBobot.setText(null);
        PrBobot.setText(null);
        SoBobot.setText(null);
        Pd_Persen.setText(null);
        Kp_Persen.setText(null);
        Pr_Persen.setText(null);
        So_Persen.setText(null);
        Lamb_max.setText(null);
        C_Indeks.setText(null);
        C_Rasio.setText(null);
        CR.setText(null);
    }//GEN-LAST:event_b_ResetActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CR;
    private javax.swing.JTextField C_Indeks;
    private javax.swing.JTextField C_Rasio;
    private javax.swing.JTextField EG1;
    private javax.swing.JTextField EG2;
    private javax.swing.JTextField EG3;
    private javax.swing.JTextField EG4;
    private javax.swing.JTextField KpBobot;
    private javax.swing.JTextField Kp_Persen;
    private javax.swing.JTextField Lamb_max;
    private javax.swing.JTextField PdBobot;
    private javax.swing.JTextField Pd_Persen;
    private javax.swing.JTextField PrBobot;
    private javax.swing.JTextField Pr_Persen;
    private javax.swing.JTextField SoBobot;
    private javax.swing.JTextField So_Persen;
    private javax.swing.JButton b_Hitung;
    private javax.swing.JButton b_Reset;
    private javax.swing.JButton b_Simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t_Jum1;
    private javax.swing.JTextField t_Jum2;
    private javax.swing.JTextField t_Jum3;
    private javax.swing.JTextField t_Jum4;
    private javax.swing.JTextField t_Jumlah1;
    private javax.swing.JTextField t_Jumlah2;
    private javax.swing.JTextField t_Jumlah3;
    private javax.swing.JTextField t_Jumlah4;
    private javax.swing.JTextField t_Kp1;
    private javax.swing.JTextField t_Kp2;
    private javax.swing.JTextField t_Kp3;
    private javax.swing.JTextField t_Kp4;
    private javax.swing.JTextField t_Kpb1;
    private javax.swing.JTextField t_Kpb2;
    private javax.swing.JTextField t_Kpb3;
    private javax.swing.JTextField t_Kpb4;
    private javax.swing.JTextField t_Pd1;
    private javax.swing.JTextField t_Pd2;
    private javax.swing.JTextField t_Pd3;
    private javax.swing.JTextField t_Pd4;
    private javax.swing.JTextField t_Pdg1;
    private javax.swing.JTextField t_Pdg2;
    private javax.swing.JTextField t_Pdg3;
    private javax.swing.JTextField t_Pdg4;
    private javax.swing.JTextField t_Pr1;
    private javax.swing.JTextField t_Pr2;
    private javax.swing.JTextField t_Pr3;
    private javax.swing.JTextField t_Pr4;
    private javax.swing.JTextField t_Pro1;
    private javax.swing.JTextField t_Pro2;
    private javax.swing.JTextField t_Pro3;
    private javax.swing.JTextField t_Pro4;
    private javax.swing.JTextField t_Sos1;
    private javax.swing.JTextField t_Sos2;
    private javax.swing.JTextField t_Sos3;
    private javax.swing.JTextField t_Sos4;
    private javax.swing.JTextField t_Sosial1;
    private javax.swing.JTextField t_Sosial2;
    private javax.swing.JTextField t_Sosial3;
    private javax.swing.JTextField t_Sosial4;
    private javax.swing.JTextField t_kodePerhitungan;
    // End of variables declaration//GEN-END:variables
}
