/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Form_Kriteria extends javax.swing.JPanel {
    private Connection conn = new Koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form Form_Kriteria
     */
    public Form_Kriteria() {
        initComponents();
        datadaftartable();
        bt_Hapus.setVisible(false);
        bt_Batal.setVisible(false);
    }
    protected void aktif(){
        t_kodeKriteria.setEnabled(true);
        t_namaKriteria.setEnabled(true);
        t_namaKriteria.requestFocus();
    }
    
    protected void kosong(){
        t_kodeKriteria.setText("");
        t_namaKriteria.setText("");
    }
    
    protected void datadaftartable(){
        Object[] Baris ={"Kode Kriteria","Nama Kriteria"};
        tabmode = new DefaultTableModel(null, Baris);
        tb_dataKriteria.setModel(tabmode);
        String sql = "select * from tb_kriteria";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
            String a = hasil.getString("kode_kriteria");
            String b = hasil.getString("nama_kriteria");
            
            
            String [] data = {a,b};
            tabmode.addRow(data);
            }
        }catch (Exception e){
        }
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_namaKriteria = new javax.swing.JTextField();
        t_kodeKriteria = new javax.swing.JTextField();
        bt_Batal = new javax.swing.JButton();
        bt_Tambah = new javax.swing.JButton();
        bt_Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dataKriteria = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 83, 25));
        jLabel5.setText("Data Kriteria");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel1.setText("Nama Kriteria");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel2.setText("Kode Kriteria");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 20));

        t_namaKriteria.setFont(new java.awt.Font("Lucida Fax", 0, 24)); // NOI18N
        t_namaKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaKriteriaActionPerformed(evt);
            }
        });
        add(t_namaKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 230, 50));

        t_kodeKriteria.setFont(new java.awt.Font("Lucida Fax", 0, 24)); // NOI18N
        t_kodeKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodeKriteriaActionPerformed(evt);
            }
        });
        add(t_kodeKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 230, 50));

        bt_Batal.setBackground(new java.awt.Color(255, 255, 255));
        bt_Batal.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        bt_Batal.setText("Batal");
        bt_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BatalActionPerformed(evt);
            }
        });
        add(bt_Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 110, 40));

        bt_Tambah.setBackground(new java.awt.Color(255, 255, 255));
        bt_Tambah.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        bt_Tambah.setForeground(new java.awt.Color(0, 153, 51));
        bt_Tambah.setText("Tambah");
        bt_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_TambahActionPerformed(evt);
            }
        });
        add(bt_Tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 110, 40));

        bt_Hapus.setBackground(new java.awt.Color(255, 255, 255));
        bt_Hapus.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        bt_Hapus.setForeground(new java.awt.Color(255, 0, 0));
        bt_Hapus.setText("Hapus");
        bt_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_HapusActionPerformed(evt);
            }
        });
        add(bt_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 110, 40));

        tb_dataKriteria.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        tb_dataKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_dataKriteria.setRowHeight(25);
        tb_dataKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataKriteriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_dataKriteria);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 1090, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void t_namaKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaKriteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaKriteriaActionPerformed

    private void t_kodeKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodeKriteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodeKriteriaActionPerformed

    private void bt_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_HapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from tb_kriteria where kode_kriteria ='"+t_kodeKriteria.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                t_namaKriteria.requestFocus();
                datadaftartable();
                bt_Hapus.setVisible(false);
                bt_Batal.setVisible(false);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" +e);
            }
        
        }   
    }//GEN-LAST:event_bt_HapusActionPerformed

    private void bt_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BatalActionPerformed
        kosong();
        bt_Tambah.setText("Tambah");
        bt_Hapus.setVisible(false);
        bt_Batal.setVisible(false);       
    }//GEN-LAST:event_bt_BatalActionPerformed

    private void bt_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_TambahActionPerformed
       if (bt_Tambah.getText().equals("Ubah")){
            try {
                String sql = "UPDATE tb_kriteria SET nama_kriteria=? WHERE kode_kriteria=?";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, t_namaKriteria.getText());
                stat.setString(2, t_kodeKriteria.getText());
                
                int rowsUpdated = stat.executeUpdate();
                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                    kosong();
                    t_kodeKriteria.requestFocus();
                    datadaftartable();
                    bt_Tambah.setText("Tambah");
                    bt_Hapus.setVisible(false);
                    bt_Batal.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            }
       }else{
        String sql = "Insert into tb_kriteria values (?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, t_kodeKriteria.getText());
                stat.setString(2, t_namaKriteria.getText());
                
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Tambah");
                kosong();
                t_kodeKriteria.requestFocus();
                datadaftartable(); 
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Di Tambah");
            }
        }  
    }//GEN-LAST:event_bt_TambahActionPerformed

    private void tb_dataKriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataKriteriaMouseClicked
        bt_Tambah.setText("Ubah");
        bt_Hapus.setVisible(true);
        bt_Batal.setVisible(true);
        int bar = tb_dataKriteria.getSelectedRow();
        String a =tabmode.getValueAt(bar, 0).toString();
        String b =tabmode.getValueAt(bar, 1).toString();
        
        t_kodeKriteria.setText(a);
        t_namaKriteria.setText(b);
    }//GEN-LAST:event_tb_dataKriteriaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Batal;
    private javax.swing.JButton bt_Hapus;
    private javax.swing.JButton bt_Tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_kodeKriteria;
    private javax.swing.JTextField t_namaKriteria;
    private javax.swing.JTable tb_dataKriteria;
    // End of variables declaration//GEN-END:variables
}
